### ISSUE TITLE
Website Feedback #1

### ISSUE THREAD

**Issue by rvno** [ChristineSchatz/ChristineSchatz.github.io#6]
Hey Christine!

Since you were so kind as to give me feedback, I thought I'd take a look at your site as well to see if I could offer you some, too! I definitely like the minimalist feel and use of a full background image, and I'm sensing that we have a similar creative mindset haha! I like how you decided to keep the same template throughout your website, I think it minimizes distractions and is definitely easy on the eyes. I'm curious to see how you could implement Parallax JS later on to enhance your site, I think it'll definitely work with your design in particular!

In terms of things you could look into, maybe experiment a bit more with color schemes to look into complimentary and opposite colors, I definitely think the blue and orange are great but they may clash a bit with the grey background. On that note, it may be helpful to change your hover effect colors from black to some other color, I thought that your icons on the bottom disappeared when I navigated to them haha. Other than that, my only other suggestion is to possibly vertically center your name on your landing page and add a photo of yourself!

Looking forward to seeing what you do with your site from here on out!

Harvey

**Comment by ChristineSchatz** [comment]
Hey Harvey!
Thank you so much for your feedback. I'm especially grateful because you have a really good eye for design. 

Thank you for your comments on the color scheme! I totally agree with you. The gray clashes and is kinda blah next to the bright blue. I'll have to experiment some. Ohhh, wow, and great observation about the black color hover effect too. Btw, I'm working on a 13-inch laptop, and I'm a little scared to go look at the site from a much larger monitor at work tomorrow! I hope the elements stay where they're supposed to be :) That said, I will clean up the positioning of my name and add a photo.

I hope we get to explore Parallax in the curriculum later, too!

Really appreciate it!

-Christine
